package pefile

enum class StorageClass(val value: Int) {

	END_OF_FUNCTION(-1),
	NULL(0),
	AUTOMATIC(1),
	EXTERNAL(2),
	STATIC(3),
	REGISTER(4),
	EXTERNAL_DEF(5),
	LABEL(6),
	UNDEFINED_LABEL(7),
	MEMBER_OF_STRUCT(8),
	ARGUMENT(9),
	STRUCT_TAG(10),
	MEMBER_OF_UNION(11),
	UNION_TAG(12),
	TYPE_DEFINITION(13),
	UNDEFINED_STATIC(14),
	ENUM_TAG(15),
	MEMBER_OF_ENUM(16),
	REGISTER_PARAM(17),
	BIT_FIELD(18),
	BLOCK(100),
	FUNCTION(101),
	END_OF_STRUCT(102),
	FILE(103),
	SECTION(104),
	WEAK_EXTERNAL(105),
	CLR_TOKEN(107);

	companion object {
		val map = values().associateBy { it.value }
	}
}