package assembler

enum class Register(val value: Int, val flags: OperandFlags) {

	RAX(0, OperandFlags { A + REG }),
	RCX(1, OperandFlags.REG),
	RDX(2, OperandFlags.REG),
	RBX(3, OperandFlags.REG),
	RSP(4, OperandFlags.REG),
	RBP(5, OperandFlags.REG),
	RSI(6, OperandFlags.REG),
	RDI(7, OperandFlags.REG),
	R8( 8, OperandFlags.REG),
	R9( 9, OperandFlags.REG),
	R10(10, OperandFlags.REG),
	R11(11, OperandFlags.REG),
	R12(12, OperandFlags.REG),
	R13(13, OperandFlags.REG),
	R14(14, OperandFlags.REG),
	R15(15, OperandFlags.REG),
	
	EAX(0, OperandFlags { A + REG }),
	ECX(1, OperandFlags.REG),
	EDX(2, OperandFlags.REG),
	EBX(3, OperandFlags.REG),
	ESP(4, OperandFlags.REG),
	EBP(5, OperandFlags.REG),
	ESI(6, OperandFlags.REG),
	EDI(7, OperandFlags.REG),
	R8D(8, OperandFlags.REG),
	R9D(9, OperandFlags.REG),
	R10D(10, OperandFlags.REG),
	R11D(11, OperandFlags.REG),
	R12D(12, OperandFlags.REG),
	R13D(13, OperandFlags.REG),
	R14D(14, OperandFlags.REG),
	R15D(15, OperandFlags.REG),

	AX(0, OperandFlags { A + REG }),
	CX(1, OperandFlags.REG),
	DX(2, OperandFlags.REG),
	BX(3, OperandFlags.REG),
	SP(4, OperandFlags.REG),
	BP(5, OperandFlags.REG),
	SI(6, OperandFlags.REG),
	DI(7, OperandFlags.REG),
	R8W(8, OperandFlags.REG),
	R9W(9, OperandFlags.REG),
	R10W(10, OperandFlags.REG),
	R11W(11, OperandFlags.REG),
	R12W(12, OperandFlags.REG),
	R13W(13, OperandFlags.REG),
	R14W(14, OperandFlags.REG),
	R15W(15, OperandFlags.REG),

	AL(0, OperandFlags { AL + REG8 }),
	CL(1, OperandFlags { CL + REG8 }),
	DL(2, OperandFlags.REG8),
	BL(3, OperandFlags.REG8),
	AH(4, OperandFlags.REG8),
	CH(5, OperandFlags.REG8),
	DH(6, OperandFlags.REG8),
	BH(7, OperandFlags.REG8),
	R8B(8, OperandFlags.REG8),
	R9B(9, OperandFlags.REG8),
	R10B(10, OperandFlags.REG8),
	R11B(11, OperandFlags.REG8),
	R12B(12, OperandFlags.REG8),
	R13B(13, OperandFlags.REG8),
	R14B(14, OperandFlags.REG8),
	R15B(15, OperandFlags.REG8),


}